name: Remove old artifacts

on:
  schedule:
    - cron: "1 1 1 * *"

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          age: "1 month"
          skip-tags: false
          skip-recent: 3
